# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_util', models.CharField(max_length=200)),
                ('prenom_util', models.CharField(max_length=200)),
                ('mail_util', models.EmailField(max_length=254)),
                ('password_util', models.CharField(max_length=50)),
                ('login_util', models.CharField(max_length=30)),
                ('grade_util', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
        ),
        migrations.CreateModel(
            name='Animer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_util', models.CharField(max_length=200)),
                ('prenom_util', models.CharField(max_length=200)),
                ('mail_util', models.EmailField(max_length=254)),
                ('password_util', models.CharField(max_length=50)),
                ('login_util', models.CharField(max_length=30)),
                ('grade_util', models.CharField(max_length=50)),
                ('diplome_appr', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_categ', models.CharField(max_length=200)),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_chap', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_cour', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_util', models.CharField(max_length=200)),
                ('prenom_util', models.CharField(max_length=200)),
                ('mail_util', models.EmailField(max_length=254)),
                ('password_util', models.CharField(max_length=50)),
                ('login_util', models.CharField(max_length=30)),
                ('grade_util', models.CharField(max_length=50)),
                ('spec_formation', models.CharField(max_length=80)),
                ('type_formation', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_form', models.CharField(max_length=80)),
                ('date_deb_form', models.DateField()),
                ('date_fin_form', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Regroupement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_group', models.DateField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_ress', models.CharField(max_length=80)),
                ('type_ress', models.CharField(max_length=50)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateField()),
                ('note_test', models.IntegerField()),
                ('id_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation')),
                ('id_util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Apprenant')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Cours'),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation'),
        ),
        migrations.AddField(
            model_name='animer',
            name='id_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation'),
        ),
        migrations.AddField(
            model_name='animer',
            name='id_util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formateur'),
        ),
    ]
